document.addEventListener("DOMContentLoaded", () => {
  const images = [];
  const timestamp = document.getElementById("timestamp");
  timestamp.value = new Date().toLocaleString();

  const imagesInput = document.getElementById("images");
  const previews = document.getElementById("previews");

  imagesInput.addEventListener("change", (e) => {
    previews.innerHTML = "";
    images.length = 0;

    Array.from(e.target.files).forEach(file => {
      const reader = new FileReader();
      reader.onload = event => {
        images.push(event.target.result);
        const img = document.createElement("img");
        img.src = event.target.result;
        img.className = "preview";
        previews.appendChild(img);
      };
      reader.readAsDataURL(file);
    });
  });

  document.getElementById("generatePDF").addEventListener("click", () => {
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF();
    let y = 10;

    const plate = document.getElementById("plate").value;
    const vehicle = document.getElementById("vehicle").value;
    const type = document.getElementById("type").value;
    const obs = document.getElementById("obs").value;
    const live = document.getElementById("live").value;
    const rec = document.getElementById("rec").value;
    const location = document.getElementById("location").value;
    const ts = timestamp.value;

    pdf.setFontSize(14);
    pdf.text(`Vehicle Report – ${plate}`, 10, y); y += 8;
    pdf.setFontSize(10);
    pdf.text(`Type: ${type}`, 10, y); y+=6;
    pdf.text(`Vehicle: ${vehicle}`, 10, y); y+=6;
    pdf.text(`Date: ${ts}`, 10, y); y+=6;
    pdf.text(`Location: ${location}`, 10, y); y+=10;

    pdf.setFontSize(11);
    pdf.text("Observations:", 10, y); y+=6;
    pdf.setFontSize(10);
    pdf.text(pdf.splitTextToSize(obs || "-", 180), 10, y); y+=obs.length*0.5 + 5;

    if(type === "Full Diagnostic"){
      pdf.setFontSize(11);
      pdf.text("Live Data / Notes:", 10, y); y+=6;
      pdf.setFontSize(10);
      pdf.text(pdf.splitTextToSize(live || "-", 180), 10, y); y+=live.length*0.5 + 5;
    }

    pdf.setFontSize(11);
    pdf.text("Recommendations:", 10, y); y+=6;
    pdf.setFontSize(10);
    pdf.text(pdf.splitTextToSize(rec || "-", 180), 10, y); y+=rec.length*0.5 + 5;

    // Add watermark
    pdf.setTextColor(57,255,20,20);
    pdf.setFontSize(60);
    pdf.text('SOS', 105, 150, {align:'center', angle:45});

    // Add images
    images.forEach(img => {
      pdf.addPage();
      pdf.addImage(img, 'JPEG', 10, 20, 180, 120);
    });

    pdf.setFontSize(8);
    pdf.setTextColor(100);
    pdf.text("This report was generated by SOS Mobile Reports. Based on what is tested, the fix cannot be guaranteed.", 10, 290);

    pdf.save(`SOS_Report_${plate}.pdf`);
  });
});